#!/usr/bin/env python3
"""Build the self-contained HTML research report on property loss and theft.

    python3 research/build_report.py

Writes research/theft-and-property-loss-report.html - one file, no external
assets, no JavaScript, no network calls. Charts are inline SVG generated by
charts.py; all figures come from data.py, which cites a primary source for each.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import charts as C  # noqa: E402
import data as D  # noqa: E402
from charts import Bar, Effect  # noqa: E402
from shell import REPORTS, Doc  # noqa: E402

OUT = REPORTS / "theft-and-property-loss-report.html"


# ------------------------------------------------------------- helpers ----

def cite(*keys: str, extra: str = "") -> str:
    """Render a figcaption source line, marking lead-verified sources."""
    bits = []
    for k in keys:
        label, org, url, kind, year = D.SOURCES[k]
        tick = " &#10003;" if k in D.VERIFIED_BY_LEAD else ""
        bits.append(f'<a href="{url}">{org}, <i>{label}</i></a> ({year}){tick}')
    src = "<b>Source:</b> " + "; ".join(bits) + "."
    return f"{src} {extra}" if extra else src


def chip(kind: str) -> str:
    m = {
        "strong": ('c-strong', 'Strong'), "mod": ('c-mod', 'Moderate'),
        "weak": ('c-weak', 'Weak'), "none": ('c-none', 'No effect'),
        "official": ('c-off', 'Official'), "academic": ('c-aca', 'Peer-reviewed'),
        "vendor": ('c-ven', 'Vendor claim'), "news": ('c-none', 'Press'),
        "nodata": ('c-none', 'No base rate'),
    }
    cls, txt = m[kind]
    return f'<span class="chip {cls}">{txt}</span>'


def pct(v: float, dp: int = 1) -> str:
    return f"{v:.{dp}f}%"


d = Doc()

# ============================================================ MASTHEAD ====

MASTHEAD = f"""
<div class="masthead">
  <div class="kicker">Research Report &middot; Property Crime &amp; Loss</div>
  <h1>How people lose their things &mdash; and why they never get them back</h1>
  <div class="standfirst">An evidence review of non-theft loss, theft methods and
  recovery, with the campus case as the first deployment context. Built from
  primary statistical sources and systematic reviews, with every headline figure
  traced to the publishing body.</div>
  <div class="meta">
    <div><b>Scope</b>US, UK &amp; EU data; university campuses</div>
    <div><b>Evidence base</b>__NSRC__ primary sources</div>
    <div><b>Figures</b>__NFIG__ charts, __NTAB__ tables</div>
    <div><b>Prepared</b>28 August 2026</div>
  </div>
</div>"""

# ============================================================ SUMMARY =====

d.h2("Executive summary", "summary")
d.p(
    "Property leaves its owner through two channels &mdash; <b>misplacement</b> and "
    "<b>theft</b> &mdash; and the instinct is to treat them as different problems. The data "
    "says they are largely the same problem wearing two hats. In both channels the "
    "dominant mechanism is a small, portable, unmarked object left briefly without a "
    "guardian. In both channels the item usually still physically exists afterwards. "
    "And in both channels it fails to come home for the same reason: <b>nothing on the "
    "object connects it to its owner, and no one who finds it has a cheap way to act.</b>",
    "lede")

d.keys([
    (pct(D.NONVEHICLE_PCT), "of the value of stolen property is recovered "
     "<b>once you exclude motor vehicles</b>. The headline recovery rate is "
     f"{D.T24_TOTAL_PCT}%, but {D.VEHICLE_SHARE_OF_RECOVERED:.0f}% of everything "
     "recovered by value is cars.", "FBI Table 24, 2019"),
    ("1.0%", "of US larceny-theft is pocket-picking and purse-snatching "
     "<i>combined</i>. Theft is overwhelmingly taken from unattended places, "
     "not off people's bodies.", "FBI UCR, 2019"),
    (pct(D.NCVS_TOTAL_REPORTED), "of US household property victimisations are "
     "reported to police at all. Seven in ten never enter the system.",
     "BJS NCVS, 2023"),
    ("23.9%", "of items handed in to Transport for London's lost property "
     "system are reclaimed by their owner &mdash; and the rate tracks whether the "
     "item carries an identity.", "TfL, 2018/19"),
])

d.box("insight", "The central finding",
      "<p>Recovery rates do not track how <i>valuable</i> an item is. They track how "
      "<b>identifiable</b> it is. Stolen motor vehicles &mdash; registered, numbered, "
      f"title-tracked &mdash; recover at <b>56.1%</b> of value. Everything else recovers at "
      f"<b>{pct(D.NONVEHICLE_PCT)}</b>. Jewellery, the second most valuable category "
      "after vehicles, recovers at <b>3.5%</b>. Inside TfL's lost property system the same "
      "pattern repeats without any thief involved: phones are reclaimed at <b>48.3%</b> and "
      "umbrellas at <b>2.3%</b>.</p>"
      "<p>That is the design brief. The binding constraint on getting property back is not "
      "surveillance, and not police capacity. It is <b>the absence of a cheap, universal link "
      "between an object and its owner, plus somewhere for a finder to discharge it.</b></p>")

d.h3("What the evidence supports")
d.ol([
    "<b>Opportunity, not skill, drives loss.</b> Campus police put theft of unattended or "
    "unsecured property at over half of all crime on their patch; a detailed campus study "
    "found 69% of thefts were from unattended bags. Pickpocketing &mdash; the archetype &mdash; "
    "is 0.6% of US larceny.",
    "<b>The criminal justice funnel leaks almost everything.</b> Of US property "
    f"victimisations, {pct(D.NCVS_TOTAL_REPORTED)} are reported, {pct(D.CLEARANCE[6][1])} of "
    "recorded larcenies are cleared, and outside vehicles most value is never recovered. "
    "Any solution that routes through policing inherits this funnel.",
    "<b>Situational measures work, but only in narrow, specifiable conditions.</b> CCTV "
    "reduces crime ~12% pooled, ~37% in car parks, and <i>not at all</i> when passively "
    "monitored. Effects concentrate in property crime, never violent crime.",
    "<b>Killing the resale market beats catching thieves.</b> When Apple shipped Activation "
    "Lock, iPhone robberies in San Francisco fell 38% while Samsung thefts rose 12%. Making "
    "an object worthless to a stranger is the strongest single lever in the record.",
    "<b>Finders are far more honest than anyone predicts.</b> In a 40-country experiment "
    "with 17,303 wallets, adding money <i>increased</i> return rates from 40% to 51%, and "
    "large sums pushed it to 72%. Both economists and the public predicted the opposite.",
    "<b>Displacement is the exception, not the rule.</b> Across 572 tests, crime displacement "
    "appeared in 26% and diffusion of benefits in 27%. Prevention rarely just moves crime.",
])

d.box("caveat", "How to read this report",
      "<p>Every figure names its base, geography and year, because theft statistics are "
      "unusually easy to misuse. <b>Police-recorded</b> counts and <b>survey-estimated</b> "
      "counts are not interchangeable &mdash; the gap between them is itself one of the "
      "findings. Where a widely repeated claim has no defensible base rate, this report says "
      "so rather than inventing a percentage; that applies to most of the colourful theft "
      "techniques in Section 5. A tick (&#10003;) in a source line marks a figure the author "
      "opened and read in the primary source personally.</p>")

# =========================================================== SECTION 1 ====

d.h2("1. The two channels: misplacement and theft", "channels")
d.p("A useful taxonomy has to be built around <i>mechanism</i>, because mechanism is what a "
    "solution attaches to. Splitting by legal category (theft vs. loss) puts a bright line "
    "through the middle of what is actually one continuum of failed guardianship.")

d.table(
    ["Channel", "Mechanism", "Does the item still exist?", "Who holds it after?",
     "What recovery requires"],
    [["<b>Misplacement</b>", "Owner sets the item down and leaves without it",
      "Almost always", "Venue, transport operator, or a stranger",
      "Owner-identity on the item, or owner finds the right lost-and-found"],
     ["<b>Opportunistic theft</b>", "Stranger takes an unattended item during a guardianship gap",
      "Usually, until resold", "Thief, then a buyer",
      "Identity plus a check at the point of resale"],
     ["<b>Predatory theft</b>",
      "Stranger targets a person or a secured container (pickpocketing, burglary, lock defeat)",
      "Usually, until resold", "Thief, then a buyer",
      "Same as above; deterrence has to happen before the act"],
     ["<b>Loss in a custody chain</b>",
      "Item handed to an operator (airline, courier) and mis-routed",
      "Yes, and it is tracked", "The operator",
      "The operator's own reconciliation system"]],
    title="A mechanism-first taxonomy of how property leaves its owner",
    sub="The first three converge on the same recovery bottleneck. Only the fourth has a "
        "counterparty who already knows the item exists and is contractually obliged to find it.",
    source="<b>Framework:</b> author's synthesis, structured on routine activity theory "
           "(a suitable target, a motivated offender, and the absence of a capable guardian) "
           "and the CRAVED model of theft-attractive goods. "
           + cite("craved", "unodc"))

d.p("The fourth channel is worth a glance precisely because it is the one that works. When an "
    "airline mishandles a bag, the bag is inside a system that knows it exists, knows who "
    "owns it, and is liable for it. The result is a mishandling rate of "
    f"{D.SITA_2024['rate_per_1000']} bags per 1,000 passengers, with about "
    f"{D.SITA_2024['resolved_48h_pct']}% of the {D.SITA_2024['total_m']} million mishandled bags "
    "resolved within 48 hours. Notably, only "
    f"{D.SITA_2024['lost_stolen']}% of mishandling events are true loss or theft &mdash; "
    f"{D.SITA_2024['delayed']}% are simply delayed. Custody plus identity plus liability turns "
    "a loss problem into a logistics problem.")
d.raw(f'<p class="srcnote">{cite("sita")} SITA is an air-transport industry supplier; these '
      "are its WorldTracer operational data weighted to IATA traffic, not independent "
      "official statistics.</p>")

# =========================================================== SECTION 2 ====

d.h2("2. Losing things without a thief", "loss")
d.p("The best public dataset on non-theft loss is Transport for London's lost property "
    f"transparency release, because it publishes both what was <i>found</i> and what was "
    f"<i>reclaimed</i>, by category. In {D.TFL_YEAR}, {D.TFL_FOUND:,} items were handed in "
    f"across the London network and {D.TFL_RECLAIMED:,} were reclaimed &mdash; "
    f"{100 * D.TFL_RECLAIMED / D.TFL_FOUND:.1f}%.")

d.fig(
    C.hbar([Bar(n, 100 * f / D.TFL_FOUND) for n, f, _ in D.TFL_ITEMS],
           unit="%", dp=1, label_w=224),
    "What people actually leave behind",
    f"Share of {D.TFL_FOUND:,} items found across the Transport for London network, {D.TFL_YEAR}.",
    cite("tfl", extra="Categories as published; the ten shown sum to the full total."))

d.p("The mix is unglamorous: paper, clothes and bags dominate. But the interesting number is "
    "not what gets lost &mdash; it is what comes back.")

_reclaim = sorted(((n, 100 * r / f) for n, f, r in D.TFL_ITEMS),
                  key=lambda x: -x[1])
d.fig(
    C.hbar([Bar(n, v, color=C.POSITIVE if v > 30 else (C.ACCENT if v > 12 else C.NEGATIVE))
            for n, v in _reclaim], unit="%", dp=1, label_w=224),
    "Reclaim rate by category \u2014 identity decides everything",
    "Percentage of found items in each category that were reclaimed by their owner. "
    "No thief is involved anywhere in this chart: every one of these items was handed in "
    "and sat waiting in a lost property office.",
    cite("tfl", extra="Reclaimed counts across the ten categories sum exactly to the "
                      f"published total of {D.TFL_RECLAIMED:,}."))

d.box("insight", "Why phones come back and umbrellas do not",
      "<p>A phone is reclaimed <b>48.3%</b> of the time. An umbrella, <b>2.3%</b>. That is a "
      "21-fold difference, and it is not explained by value alone &mdash; jewellery is "
      "valuable and is reclaimed only <b>3.4%</b> of the time.</p>"
      "<p>What separates them is <b>two-sided identifiability</b>. A phone announces its owner "
      "(it rings, it has a lock screen, its owner knows exactly where they were) <i>and</i> its "
      "owner is motivated enough to chase it. Jewellery is valuable but anonymous and its loss "
      "is often not noticed at a specific place or time. An umbrella is anonymous and not worth "
      "a trip. <b>Recovery needs both a link to the owner and a motivated claimant; value alone "
      "supplies only the second.</b></p>")

_svc = sorted(D.TFL_SERVICES, key=lambda s: -s[1])[:6]
d.fig(
    C.vbar([Bar(n, 100 * f / D.TFL_FOUND) for n, f, _ in _svc], unit="%", dp=1,
           height=280, label_lines=2),
    "Where items are lost across the network",
    "Buses alone account for over half of all items handed in &mdash; a reminder that loss "
    "concentrates wherever people transition between spaces while carrying things.",
    cite("tfl"))

d.h3("Time is the enemy of recovery")
d.p("Lost property systems are not archives. TfL holds ordinary property for "
    f"<b>{D.TFL_HOLD_MONTHS} months</b> and cash for <b>{D.TFL_CASH_HOLD_MONTHS} months</b>, "
    "after which unclaimed items are donated to charity or sold at public auction. New York's "
    "Metro-North allows 5&ndash;7 business days simply for an item to reach the facility, holds "
    "property for a minimum of 90 days, and reports that the vast majority of items that are "
    "returned are returned within a week. The practical window in which a reunion is possible "
    "is short, and it opens <i>before</i> most owners work out where to look.")
d.raw(f'<p class="srcnote">{cite("tfl", "mta_mnr")}</p>')

d.h3("Strangers return things far more often than anyone expects")
d.p("The single most useful behavioural result for anyone designing a recovery system is the "
    f"Cohn et al. field experiment published in <i>Science</i>. Researchers turned in "
    f"<b>{D.COHN_N:,} wallets</b> at banks, museums, post offices, hotels and public offices "
    f"across <b>{D.COHN_CITIES} cities in {D.COHN_COUNTRIES} countries</b>, varying only "
    "whether the wallet contained money, and measured whether the recipient emailed the owner "
    "within 100 days.")

d.fig(
    C.vbar([Bar(n, v, color=C.PALETTE[i]) for i, (n, v) in enumerate(D.COHN_BIGMONEY)],
           unit="%", height=270, label_lines=2),
    "Adding money makes people <i>more</i> likely to return a lost wallet",
    "Reporting rates in the three-country sub-sample (US, UK, Poland) where a large-sum "
    "condition was run. Globally the no-money rate was 40% and the money rate 51%, with the "
    "increase appearing in 38 of 40 countries.",
    cite("cohn", extra="All pairwise differences p&lt;0.0001. Country averages ranged from "
                       f"{D.COHN_COUNTRY_RANGE[0]}% to {D.COHN_COUNTRY_RANGE[1]}%."))

d.box("win", "Three design implications from the wallet experiment",
      "<ul>"
      "<li><b>Do not assume finders are the problem.</b> Baseline honesty is high and rises "
      "with stakes. The bottleneck is contactability, not morality.</li>"
      f"<li><b>Adding a key raised reporting by {D.COHN_KEY_EFFECT} percentage points</b> even "
      "though a key is worthless to the finder. Signalling that the loss <i>hurts someone</i> "
      "motivates return &mdash; a lost-item tag should say who it belongs to, not just offer a "
      "reward.</li>"
      "<li><b>Both the public and professional economists predicted the opposite result.</b> "
      "Intuitions about finder behaviour are unreliable; design against the data.</li>"
      "</ul>")

# =========================================================== SECTION 3 ====

d.h2("3. Theft at scale: what the official numbers say", "scale")
d.p("The US Uniform Crime Reporting programme provides the cleanest categorical breakdown of "
    f"theft anywhere. In 2019 there were an estimated <b>{D.LARCENY_TOTAL:,}</b> larceny-thefts "
    f"nationwide &mdash; a rate of {D.LARCENY_RATE_100K:,.1f} per 100,000 inhabitants, and "
    f"{D.LARCENY_SHARE_OF_PROPERTY}% of all property crime.")

d.fig(
    C.hbar([Bar(n, v, color=C.NEGATIVE if "picking" in n or "snatching" in n else None)
            for n, v in D.LARCENY_MIX], unit="%", dp=1, label_w=250),
    "Where theft actually happens",
    f"Percent distribution of {D.LARCENY_TOTAL:,} estimated US larceny-thefts, 2019. "
    "The two categories in red are thefts taken directly from a person.",
    cite("fbi_larceny"))

d.box("warn", "The pickpocket is a rounding error",
      "<p>Pocket-picking (0.6%) and purse-snatching (0.4%) together are <b>1.0%</b> of US "
      "larceny. Meanwhile theft from motor vehicles (27.0%), theft from buildings (10.0%), "
      "shoplifting (22.2%) and the residual 'all other larceny' (29.9%) &mdash; overwhelmingly "
      "thefts of items left somewhere &mdash; make up the bulk of the total.</p>"
      "<p>Public imagination, and a lot of product design, is aimed at the skilled thief working "
      "a crowd. The actual adversary is a person who walks past an unattended thing. Any "
      "hackathon solution optimised for defeating a professional pickpocket is optimising "
      "against 1% of the problem.</p>")

d.h3("Most theft never reaches the police at all")
d.p("Police-recorded statistics measure reporting behaviour as much as criminal behaviour. The "
    "US National Crime Victimization Survey interviews households directly and therefore counts "
    f"crimes the police never hear about. In 2023 it estimated <b>{D.NCVS_TOTAL:,}</b> property "
    f"victimisations, a rate of {D.NCVS_TOTAL_RATE} per 1,000 households &mdash; and found that "
    f"only <b>{pct(D.NCVS_TOTAL_REPORTED)}</b> were reported to police, down from "
    f"{pct(D.NCVS_TOTAL_REPORTED_2022)} the previous year.")

d.table(
    ["Crime type", "Victimisations (2023)", "Rate per 1,000 households", "% reported to police"],
    [[n, f"{v:,}", f"{r}", f"<b>{p}%</b>"] for n, v, r, p in D.NCVS_2023]
    + [["<b>All property crime</b>", f"<b>{D.NCVS_TOTAL:,}</b>", f"<b>{D.NCVS_TOTAL_RATE}</b>",
        f"<b>{pct(D.NCVS_TOTAL_REPORTED)}</b>"]],
    title="US property victimisation and reporting, 2023",
    sub="Survey estimates, not police records. Note the spread in reporting: motor vehicle "
        "theft is reported nearly three times as often as ordinary theft, because an insurance "
        "claim and a title transfer both require a police report.",
    num_cols={1, 2, 3},
    source=cite("bjs", extra="NCVS tables 2 and 4. Rates are per 1,000 households."))

d.box("insight", "Reporting rates are an incentive readout",
      f"<p>Motor vehicle theft is reported at <b>{D.NCVS_2023[3][3]}%</b>; ordinary theft at "
      f"<b>{D.NCVS_2023[0][3]}%</b>. The difference is not how upset the victim is. It is that "
      "a car has a registration, an insurer, and a paperwork process that <i>requires</i> a "
      "police report. Where infrastructure makes reporting worthwhile, people report. The UK "
      "data shows the same shape: domestic burglary is reported at 57.7% and 'other theft of "
      "personal property' at 25.2%.</p>")

_uk = sorted(D.ONS_REPORTING, key=lambda x: -x[1])
d.fig(
    C.hbar([Bar(n, v, color=C.PALETTE[0] if v > 40 else C.PALETTE[1]) for n, v in _uk],
           unit="%", dp=1, label_w=262),
    "UK: what share of victims tell the police",
    "Crime Survey for England and Wales, year ending March 2024. Survey-based, so the "
    "denominator is incidents victims report to interviewers, not incidents police recorded.",
    cite("ons_d10", extra="Table D10. The snatch-theft reporting rate is suppressed by ONS "
                          "disclosure control (unweighted base of 34), so it cannot be shown."))

d.h3("The same pattern outside the US")
d.p("England and Wales recorded a sharp rise in theft from the person: the Crime Survey "
    f"estimated <b>{D.ONS['csew_theft_person']:,}</b> incidents in the year to March 2024 "
    f"against {D.ONS['csew_theft_person_prev']:,} the year before, a 40% increase, while police "
    f"recorded only {D.ONS['police_theft_person']:,} such offences &mdash; roughly "
    f"{100 * D.ONS['police_theft_person'] / D.ONS['csew_theft_person']:.0f}% of the survey "
    f"estimate. Across the EU, {D.EUROSTAT_EU_THEFTS_2024:,} thefts were recorded by police in "
    "2024. National rates differ enormously "
    + ", ".join(f"({n} {v:,.0f} per 100,000)" for n, v in D.EUROSTAT_RATES)
    + " but Eurostat cautions these reflect differences in law, recording practice and "
      "reporting propensity as much as in underlying crime.")
d.raw(f'<p class="srcnote">{cite("ons", "eurostat")}</p>')

# =========================================================== SECTION 4 ====

d.h2("4. The recovery funnel: why property never comes home", "funnel")
d.p("Put the numbers in sequence and the picture is stark. Start with 100 property crimes as "
    "victims experience them, and follow how many produce a returned object.")

_f_report = D.NCVS_TOTAL_REPORTED
_f_clear = _f_report * D.CLEARANCE[6][1] / 100
_f_recover = _f_report * D.NONVEHICLE_PCT / 100
d.fig(
    C.funnel([
        ("Property crimes experienced", 100.0, "as measured by victim survey"),
        ("Reported to police", _f_report, f"NCVS 2023: {pct(_f_report)} of victimisations"),
        ("Recorded offence cleared by arrest", _f_clear,
         f"applying the {D.CLEARANCE[6][1]}% larceny clearance rate"),
        ("Value recovered (excluding vehicles)", _f_recover,
         f"applying the {pct(D.NONVEHICLE_PCT)} non-vehicle recovery rate"),
    ], unit="", title=""),
    "The attrition funnel for stolen property",
    "Illustrative composition of independently sourced US rates, indexed to 100 victimisations. "
    "The stages come from different collections (a victim survey, police clearance records and "
    "an agency property-value return) and different years, so this is a scale diagram of "
    "attrition, not a single cohort followed through.",
    cite("bjs", "fbi_clear", "fbi_t24",
         extra="<b>Method:</b> composition of published rates by the author; treat as "
               "order-of-magnitude, not a point estimate."))

d.p("Each stage of that funnel is a separate design opportunity, and they are not equally "
    "tractable. Raising the clearance rate means more police. Raising the reporting rate means "
    "giving victims a reason to bother. Raising the recovery rate means making found property "
    "matchable. The last is the only one a small team can move.")

d.h3("The evidence that identity, not value, drives recovery")
_t24_bars = [Bar(n, p, color=C.POSITIVE if p > 30 else (C.ACCENT if p > 10 else C.NEGATIVE))
             for n, s, r, p in D.T24]
d.fig(
    C.hbar(_t24_bars, unit="%", dp=1, label_w=234),
    "Percentage of stolen value recovered, by property type",
    f"US, 2019, {D.T24_AGENCIES:,} reporting agencies covering an estimated population of "
    f"{D.T24_POPULATION:,}. Registered, serial-numbered, title-tracked property recovers. "
    "Anonymous property does not.",
    cite("fbi_t24"))

d.table(
    ["Measure", "Value", "What it shows"],
    [["Total property stolen", f"${D.T24_TOTAL_STOLEN:,}", "Reported value, 2019"],
     ["Total recovered", f"${D.T24_TOTAL_RECOVERED:,}",
      f"{D.T24_TOTAL_PCT}% &mdash; the figure usually quoted"],
     ["Motor vehicles recovered", f"${D.T24[0][2]:,}",
      f"<b>{D.VEHICLE_SHARE_OF_RECOVERED:.1f}% of everything recovered by value</b>"],
     ["Non-vehicle property stolen", f"${D.NONVEHICLE_STOLEN:,}", "The rest of the problem"],
     ["Non-vehicle property recovered", f"${D.NONVEHICLE_RECOVERED:,}",
      f"<b>{pct(D.NONVEHICLE_PCT, 2)}</b> &mdash; the real recovery rate for ordinary goods"]],
    title="Unpacking the headline recovery rate",
    sub="Derived by the author from the published category rows. The widely quoted "
        f"'{D.T24_TOTAL_PCT}% of stolen property is recovered' is an artefact of vehicles being "
        "in the same denominator as phones and jewellery.",
    num_cols={1},
    source=cite("fbi_t24", extra="<b>Derivation:</b> non-vehicle figures are total minus the "
                                 "'locally stolen motor vehicles' row; arithmetic performed in "
                                 "<code>research/data.py</code>."))

d.box("insight", "Why cars are the exception that proves the rule",
      "<p>A car is <i>the</i> most valuable, most attractive, most professionally targeted "
      "consumer object most people own. By the CRAVED model it should be the hardest to protect. "
      "Yet it recovers at 56% while a laptop recovers with everything else at around 8%.</p>"
      "<p>The difference is a stack of boring infrastructure: a unique visible identifier (VIN "
      "and plate), a mandatory owner registry, a title system that makes resale to an innocent "
      "buyer difficult, and a police database that is checked routinely rather than on request. "
      "<b>Nothing about that stack is technically hard. It simply does not exist for anything "
      "smaller than a vehicle.</b></p>")

# =========================================================== SECTION 5 ====

d.h2("5. Methods: how strangers actually take things", "methods")
d.p("This section carries a health warning. Theft techniques are extensively catalogued in "
    "police guidance and journalism, but <b>most have no defensible prevalence statistic</b>. "
    "Official crime statistics record legal categories, not tradecraft: there is no national "
    "dataset recording what proportion of bike thefts used an angle grinder. Where a base rate "
    "exists it is given; where it does not, the entry is marked "
    + chip("nodata") + " rather than filled with an invented number.")

_M = [
    ("<b>Unattended-item taking</b>",
     "Item left on a table, in a library carrel, on a gym bench or beside a seat; taken during "
     "the guardianship gap. No skill, no tools, no confrontation.",
     "Dominant on campus: <b>69%</b> of thefts in the UW-Madison study were from unattended "
     "bags; University of Miami Police put unattended/unsecured theft at <b>over half</b> of "
     "all campus crime.", "uwpd"),
    ("<b>Theft from vehicles</b>",
     "Window smash or door test, targeting visible items. The single largest named larceny "
     "category in the US.",
     "<b>27.0%</b> of US larceny-theft; a further <b>6.5%</b> is parts and accessories.",
     "fbi_larceny"),
    ("<b>Shoplifting</b>",
     "Concealment or walk-out from retail; increasingly organised for resale.",
     "<b>22.2%</b> of US larceny. In England and Wales police recorded "
     f"<b>{D.ONS['police_shoplifting']:,}</b> shoplifting offences in the year to March 2024, "
     "up 30%.", "fbi_larceny"),
    ("<b>Theft from buildings</b>",
     "Entering an unsecured or public building (dorm, office, residence common room) and taking "
     "property without forced entry.",
     "<b>10.0%</b> of US larceny.", "fbi_larceny"),
    ("<b>Bicycle theft</b>",
     "Lock defeat by bolt cropper, angle grinder or leverage; lifting the bike with the lock "
     "still attached; stripping quick-release wheels and components.",
     "<b>3.1%</b> of US larceny. At Indiana University, "
     f"<b>{D.IU_BIKE['locked_outdoors']}%</b> of stolen bikes were locked outdoors and only "
     f"<b>{D.IU_BIKE['u_lock']}%</b> used a U-lock. Which tool was used is "
     + chip("nodata"), "iu"),
    ("<b>Pocket-picking</b>",
     "Stall or block, bump-and-distract, team roles separating the lift from the hand-off. "
     "Concentrated in transit, escalators, crowds and festivals.",
     "<b>0.6%</b> of US larceny. In the UK, stealth theft from the person is reported to police "
     "<b>42.1%</b> of the time. Sub-technique shares are " + chip("nodata"), "fbi_larceny"),
    ("<b>Snatch theft</b>",
     "Grab and run, including moped- and e-bike-enabled phone snatching in dense city centres.",
     "<b>0.4%</b> of US larceny (purse-snatching). UK snatch figures are suppressed by ONS "
     "disclosure control at an unweighted base of 34.", "ons_d10"),
    ("<b>Distraction theft</b>",
     "Map, petition, spilled drink or 'is this your money?' routines that move the victim's "
     "attention off their property for a few seconds.",
     chip("nodata") + " Not separately coded in any official collection reviewed.", None),
    ("<b>Tailgating into secured space</b>",
     "Following an authorised person through a controlled door, or presenting as staff or "
     "contractor, to reach unattended property inside.",
     chip("nodata") + " Widely described in campus security guidance; no prevalence data found.",
     None),
    ("<b>Passcode-then-snatch</b>",
     "Shoulder-surf the phone passcode in a bar or on transit, then steal the device and use "
     "the passcode to change the account password, disable Find My, and reach banking and "
     "saved-password apps before the owner can react.",
     "Mechanism confirmed by Apple's own countermeasure documentation; no public incidence rate.",
     "apple_sdp"),
]
d.table(
    ["Method", "How it works", "Prevalence evidence"],
    [[m, h, p] for m, h, p, _ in _M],
    title="Theft methods, honestly graded",
    sub="Ordered by evidenced prevalence where a base rate exists, then by how often the method "
        "appears in police guidance. Entries marked 'no base rate' are real methods with no "
        "trustworthy denominator &mdash; a gap in the official statistics, not in the phenomenon.",
    source=cite("fbi_larceny", "ons_d10", "uwpd", "iu", "apple_sdp"))

d.box("warn", "The digital-physical attack chain deserves specific attention",
      "<p>The most consequential modern theft method is not about the object at all. An offender "
      "who observes a phone passcode and then steals the phone can change the account password, "
      "turn off device location, lock the owner out of their own recovery tools, and reach "
      "saved payment credentials. The device is the least valuable thing taken.</p>"
      "<p>Apple's response, <b>Stolen Device Protection</b> (iOS 17.3 and later, and it must be "
      "enabled <i>before</i> the theft), is instructive as a design pattern: when the phone is "
      "away from familiar locations, sensitive actions require Face ID or Touch ID with "
      "<b>no passcode fallback</b>, and critical actions such as changing the account password "
      "require biometric authentication, a <b>one-hour security delay</b>, and then biometric "
      "authentication again. Find My cannot be switched off while it is active.</p>"
      f"<p>The generalisable principle: <b>knowledge of a secret should not be sufficient to "
      "sever an object from its owner.</b> Add a delay, a second factor, and a location "
      f"context. {cite('apple_sdp')}</p>")

d.h3("Which items get targeted, and why")
d.p("Ronald Clarke's <b>CRAVED</b> model remains the best predictor of what gets stolen: goods "
    "are targeted when they are <b>C</b>oncealable, <b>R</b>emovable, <b>A</b>vailable, "
    "<b>V</b>aluable, <b>E</b>njoyable and <b>D</b>isposable. The last term is the operative "
    "one for solution design. <i>Disposable</i> means there is a working resale channel. Remove "
    "disposability and the other five stop mattering &mdash; which is exactly what the "
    "smartphone kill-switch did, and exactly why vehicles, despite scoring high on every other "
    "letter, are recovered so often.")
d.raw(f'<p class="srcnote">{cite("craved")}</p>')

# =========================================================== SECTION 6 ====

d.h2("6. The campus case", "campus")
d.p("Universities are the right first deployment context for a structural reason: they are "
    "dense, closed-ish communities with a shared identity system, a shared physical estate, "
    "high-value portable electronics, and a population that moves constantly between spaces "
    "while carrying everything it owns. They are also, unfortunately, badly measured.")

d.box("warn", "The Clery Act blind spot",
      "<p>US institutions must publish campus crime statistics under the Clery Act, and the "
      "primary reportable offence categories include <b>burglary, motor vehicle theft and "
      "arson</b> &mdash; but <b>ordinary larceny-theft is not a primary Clery-reportable "
      "category</b>. It appears only in the hate-crime schedule.</p>"
      "<p>The practical consequence: the single most common crime on campus is structurally "
      "invisible in the one dataset that covers every US institution. USC's annual security "
      "report, for example, tabulates burglary and motor vehicle theft on campus, but ordinary "
      "larceny is absent from its criminal offences table entirely. Any analysis built only on "
      f"Clery data will systematically miss the actual problem. {cite('fsa', 'usc')}</p>")

d.fig(
    C.hbar([Bar(n, 100 * v / D.NCES_TOTAL_2021, note=f"{v:,}") for n, v, _ in D.NCES_MIX],
           unit="%", dp=1, label_w=210),
    "What Clery data does capture",
    f"Share of {D.NCES_TOTAL_2021:,} on-campus criminal incidents reported by degree-granting "
    "Title IV institutions, 2021. Absolute counts shown inside each bar. Note that theft is "
    "not on this list &mdash; not because it does not happen, but because it is not collected.",
    cite("nces", extra="NCES notes that under-reporting means these figures likely do not "
                       "capture all incidents."))

d.fig(
    C.line([("Rate per 10,000 FTE", [v for _, v in D.NCES_RATE_TREND], C.PALETTE[0])],
           [y for y, _ in D.NCES_RATE_TREND], unit="", height=250, title=""),
    "Reported on-campus crime rate over time",
    "Total Clery-reportable on-campus incidents per 10,000 full-time-equivalent students. The "
    "2020 trough reflects emptied campuses during the pandemic, and 2021 shows partial "
    "reversion &mdash; a reminder that campus crime tracks occupancy closely.",
    cite("nces"))

d.h3("What institutions that do publish larceny actually see")
d.p("Georgia Tech's police department publishes a full Part I crime table, larceny included. "
    "The result is unambiguous.")

d.fig(
    C.stacked([
        ("2023", [D.GT_2023["larceny"], D.GT_2023["motor_vehicle_theft"],
                  D.GT_2023["burglary"], D.GT_2023["arson"]]),
        ("2022", [D.GT_2022["larceny"], D.GT_2022["motor_vehicle_theft"],
                  D.GT_2022["burglary"], D.GT_2022["arson"]]),
    ], ["Larceny", "Motor vehicle theft", "Burglary", "Arson"], unit="", label_w=70),
    "Georgia Tech campus property crime composition",
    f"Incident counts. Larceny was {D.GT_LARCENY_SHARE_PROPERTY:.1f}% of campus property "
    f"crime in 2023 and {D.GT_LARCENY_SHARE_2022:.1f}% in 2022 &mdash; and "
    f"{D.GT_LARCENY_SHARE_PARTI:.1f}% of all Part I crime including violent offences. Motor "
    "vehicle theft counts include scooters, which UCR rules classify as motor vehicles.",
    cite("gtpd", extra="Shares computed by the author from the published counts "
                       f"({D.GT_2023['larceny']} of {D.GT_PROPERTY_2023} property offences)."))

d.p("This is the number the Clery dataset cannot show you: <b>roughly six in ten campus crimes "
    "are ordinary theft</b>. And the University of Miami Police Department states plainly that "
    "theft of unattended or unsecured property alone accounts for over half of all crime on its "
    "Coral Gables campus.")

d.h3("The best-documented campus theft study")
d.p("UW-Madison's police department ran a problem-oriented policing project on textbook theft "
    "after incidents rose 164% in a year. Its value here is that it recorded <i>mechanism</i> "
    "and <i>location</i>, which almost no campus dataset does.")

d.raw('<div class="two">')
d.fig(
    C.hbar([Bar(n, v) for n, v in D.UW_TEXTBOOK], unit="%", label_w=196, width=560, row_h=26),
    "Mechanism of campus textbook theft",
    "Share of reported incidents.",
    cite("uwpd"))
d.fig(
    C.hbar([Bar(n, v) for n, v in D.UW_LOCATIONS], unit="%", label_w=196, width=560, row_h=26),
    "Where it happened",
    "Share of reported incidents. Theft concentrates in busy, semi-public study and social "
    "buildings &mdash; not isolated corners.",
    cite("uwpd"))
d.raw("</div>")

d.box("win", "The intervention that worked, and why it is the model",
      "<p>UW-Madison's police did not add cameras or patrols. They identified that stolen "
      "textbooks were being resold for cash to local buy-back shops, and pursued a <b>city "
      "ordinance regulating second-hand book purchases</b> &mdash; requiring seller "
      "identification and holding periods.</p>"
      f"<p>Result: textbook theft incidents fell <b>{abs(D.UW_ORDINANCE['incidents'])}%</b> and "
      f"books stolen fell <b>{abs(D.UW_ORDINANCE['books'])}%</b> in the comparable half-year "
      "after implementation. They attacked <b>disposability</b> &mdash; the D in CRAVED &mdash; "
      f"rather than the theft event itself. {cite('uwpd')}</p>"
      "<p>The report also notes students frequently did not report thefts because they had no "
      "confidence anything would be recovered, which is the reporting-rate problem in "
      "microcosm.</p>")

d.h3("Campus bicycle theft: a complete failure case")
d.p("Indiana University surveyed its community about bike theft in autumn 2024 "
    f"({D.IU_BIKE['respondents']} respondents, {D.IU_BIKE['owners']} of whom had owned a bike "
    f"in Bloomington in the past five years, yielding {D.IU_BIKE['incidents']} reported "
    "incidents). The result is a clean picture of a recovery system that does not function.")

d.fig(
    C.hbar([
        Bar("Stolen bikes locked outdoors", D.IU_BIKE["locked_outdoors"], color=C.PALETTE[7]),
        Bar("Incidents involving students", D.IU_BIKE["student_involved"], color=C.PALETTE[7]),
        Bar("Victims who reported to police", D.IU_BIKE["reported"], color=C.PALETTE[0]),
        Bar("Victims who did not report at all", D.IU_BIKE["not_reported"], color=C.ACCENT),
        Bar("Stolen bikes that were registered", D.IU_BIKE["registered"], color=C.ACCENT),
        Bar("Stolen bikes secured with a U-lock", D.IU_BIKE["u_lock"], color=C.ACCENT),
        Bar("Stolen bikes recovered", D.IU_BIKE["recovered"], color=C.NEGATIVE),
    ], unit="%", label_w=246),
    "Bicycle theft at Indiana University Bloomington",
    "Self-reported survey, autumn 2024. Read the last bar against the third: even among the "
    "58% who did report to police, recovery sat at 10% overall.",
    cite("iu", extra="Self-report survey; not a census of incidents. Seasonality was "
                     + ", ".join(f"{m} {v}%" for m, v in D.IU_SEASON)
                     + " of reported incidents, concentrated at the start of the academic year, "
                       "with most thefts between 6pm and 6am."))

d.box("insight", "Registration only helps if it is checked",
      f"<p><b>{D.IU_BIKE['registered']}%</b> of the stolen bikes <i>were</i> registered, and "
      f"only <b>{D.IU_BIKE['recovered']}%</b> were recovered. Registration on its own is not a "
      "recovery mechanism &mdash; it is only the first half of one. The second half is a "
      "routine, low-friction check at the moments a stolen bike surfaces: resale, impound, "
      "abandonment, campus racks. Building the registry is the easy part and the part everyone "
      "builds.</p>")

d.p("The seasonality finding is directly actionable for a campus deployment: "
    f"{D.IU_SEASON[0][1]}% of incidents fell in August and {D.IU_SEASON[1][1]}% in September. "
    "Intervention effort concentrated on the first six weeks of the academic year addresses "
    "roughly two-fifths of the annual problem, at a moment when new students are also most "
    "reachable.")

# =========================================================== SECTION 7 ====

d.h2("7. What currently works, measured honestly", "works")
d.p("This section reports effect sizes from systematic reviews and meta-analyses rather than "
    "vendor claims. Negative values mean less crime. Bars show published confidence intervals; "
    "where an interval crosses zero, the intervention did not produce a statistically "
    "significant effect no matter how popular it is.")

d.fig(
    C.effects([Effect(lbl, v, lo, hi) for lbl, v, lo, hi, n, g, note in D.EFFECTS],
              vmin=-60, vmax=10, label_w=252),
    "Measured crime-reduction effects of situational interventions",
    "Point estimates with published confidence intervals, converted from odds ratios and "
    "relative effect sizes to percentage change in crime in treatment versus control areas.",
    cite("piza", "lighting",
         extra="CCTV rows: 76 studies, random-effects model, 95% CIs. Lighting rows: 17 "
               "studies, 90% CIs as published. Percentage change computed as the inverse of "
               "the published ratio."))

d.table(
    ["Intervention", "Effect", "Studies", "Evidence", "Published statistic"],
    [[lbl, f"<b>{v:+.0f}%</b>", str(n), chip(g), f"<small>{note}</small>"]
     for lbl, v, lo, hi, n, g, note in D.EFFECTS],
    title="Effect sizes in detail",
    sub="'No effect' means the confidence interval includes zero, not that the intervention was "
        "shown to be harmful.",
    num_cols={1, 2},
    source=cite("piza", "lighting"))

d.box("insight", "Four rules that fall out of the meta-analyses",
      "<ol>"
      "<li><b>Passive cameras do nothing.</b> Actively monitored CCTV reduces crime ~15%; "
      "passively monitored CCTV has no significant effect at all. A camera nobody watches is "
      "set dressing.</li>"
      "<li><b>Bundles beat single measures.</b> CCTV deployed with other interventions achieved "
      "a ~34% reduction; CCTV alone was not statistically significant.</li>"
      "<li><b>Enclosed, bounded spaces respond; open ones do not.</b> Car parks ~37%, "
      "residential ~12%, city centres not significant. A campus building, bike compound or "
      "library floor is much closer to a car park than to a city centre.</li>"
      "<li><b>These are property-crime tools.</b> Effects on violent crime were not significant "
      "in either review. Do not oversell the safety case.</li>"
      "</ol>")

d.h3("The strongest single case: destroying the resale market")
d.p(f"On {D.SOS_DATE} Apple shipped Activation Lock, which renders a stolen iPhone unusable "
    "without the owner's credentials. Because Samsung devices lacked an equivalent at the time, "
    "the change created a natural comparison.")

d.fig(
    C.hbar([Bar(f"{city} \u2014 {what}", abs(v), color=C.POSITIVE)
            for city, what, v in D.SOS]
           + [Bar(f"{city} \u2014 Samsung thefts (comparison)", v, color=C.NEGATIVE)
              for city, v in D.SOS_SAMSUNG],
           unit="%", label_w=300),
    "Change in device theft after Activation Lock shipped",
    "Green bars are reductions in Apple-device theft; red bars are simultaneous increases in "
    "Samsung-device theft in the same cities and periods. Comparisons are the months following "
    f"{D.SOS_DATE} against the equivalent prior period.",
    cite("sos", extra="<b>Caveat:</b> these are uncontrolled administrative trends published by "
                      "a law-enforcement initiative, with no confidence intervals and no "
                      "controls for concurrent trends. The report itself says the figures "
                      "'appear to' validate the approach. Treat as strong suggestive evidence, "
                      "not as a causal estimate."))

d.p("The mechanism is the one that matters most for a hackathon: <b>Apple did not prevent a "
    "single theft attempt. It made the object worthless to the thief.</b> Offenders switched "
    "targets rather than persisting &mdash; which is displacement, and which is also exactly "
    "what you want when the displaced-to target then gets the same protection.")

d.h3("Does prevention just move crime around?")
d.p("This is the standard objection to every situational measure, and it has been tested at "
    f"scale. Guerette and Bowers reviewed <b>{D.GUERETTE['studies']} studies</b> containing "
    f"<b>{D.GUERETTE['examinations']} separate displacement or diffusion tests</b>.")

d.fig(
    C.hbar([
        Bar("Displacement observed", 100 * D.GUERETTE["displacement"] / D.GUERETTE["examinations"],
            color=C.NEGATIVE),
        Bar("Diffusion of benefits observed",
            100 * D.GUERETTE["diffusion"] / D.GUERETTE["examinations"], color=C.POSITIVE),
        Bar("Spatial displacement (spatial tests only)",
            100 * D.GUERETTE["spatial_disp"] / D.GUERETTE["spatial_n"], color=C.NEGATIVE),
        Bar("Spatial diffusion (spatial tests only)",
            100 * D.GUERETTE["spatial_diff"] / D.GUERETTE["spatial_n"], color=C.POSITIVE),
    ], unit="%", dp=0, label_w=280),
    "Displacement is less common than diffusion of benefits",
    f"Share of {D.GUERETTE['examinations']} tests across {D.GUERETTE['studies']} studies. "
    "'Diffusion of benefits' means crime <i>also</i> fell in nearby areas that were not treated.",
    cite("guerette", extra="Piza et al. found the same pattern for CCTV specifically: of "
                           f"{D.PIZA_DISPLACEMENT['tested']} studies with an adjacent control "
                           f"area, {D.PIZA_DISPLACEMENT['displacement']} found displacement "
                           f"while {D.PIZA_DISPLACEMENT['diffusion']} found diffusion of "
                           "benefits. " + cite("piza")))

# =========================================================== SECTION 8 ====

d.h2("8. What is popular but weakly evidenced", "weak")
d.p("An honest report has to name the interventions whose evidence does not match their "
    "reputation, because these are exactly where a hackathon team will be tempted to go.")

d.table(
    ["Approach", "Claim", "What the evidence actually shows", "Verdict"],
    [
     ["<b>Property registries</b>",
      "Register your serial numbers; police will match recovered goods to you.",
      f"Immobilise reports over {D.IMMOBILISE['users_m']}m users and "
      f"{D.IMMOBILISE['items_m']}m registered items since {D.IMMOBILISE['since']}, and its "
      "police-affiliated promoter says officers routinely check it. But no recovery numerator, "
      "no denominator of checks, and no independent utilisation audit was located. Immobilise's "
      "own illustrative success story is explicitly labelled fictitious. At Indiana University "
      f"{D.IU_BIKE['registered']}% of stolen bikes were registered and {D.IU_BIKE['recovered']}% "
      "were recovered.", chip("weak")],
     ["<b>Passive CCTV</b>", "Cameras deter theft.",
      "Passively monitored CCTV: OR 1.015, 95% CI .954&ndash;1.081, not significant across 11 "
      "studies. Active monitoring is what carries the effect.", chip("none")],
     ["<b>CCTV in open public space</b>", "Cameras make the campus safer.",
      "City and town centre schemes: not significant (p=.107). Effects on violent crime: not "
      "significant (p=.320).", chip("none")],
     ["<b>Bluetooth trackers as recovery tools</b>",
      "Attach a tracker and you will get your item back.",
      "The crowdsourced network is real and well characterised, but measured performance is "
      f"density-bound: median {D.FINDMY['upload_median_min']}-minute delay between a finder "
      f"observing a tag and the report reaching the owner, {D.FINDMY['walk_raw_m']:.0f}m mean "
      f"error walking in a city versus {D.FINDMY['train_raw_m']:.0f}m on a train and "
      f"{D.FINDMY['car_raw_m']:.0f}m in a car with only {D.FINDMY['car_reports']} reports over "
      "an hour. Location is not custody: knowing where your bike is does not get it back.",
      chip("mod")],
     ["<b>Computer-vision abandoned-object detection</b>",
      "Cameras can spot an unattended bag or a theft in progress.",
      "The canonical benchmark result correctly flagged "
      f"{D.PETS['correct_alarms']} of {D.PETS['sequences']} staged sequences with localisation "
      f"error {D.PETS['localisation_lo']}&ndash;{D.PETS['localisation_hi']}m &mdash; but that is "
      "seven acted scenes on one camera, with a false positive from a moving bin and a miss when "
      "the owner never separated. No independent field accuracy evidence for commercial systems "
      "was located; vendor accuracy claims are unaudited.", chip("weak")],
     ["<b>Smart parcel lockers</b>", "Lockers eliminate package theft.",
      "Plausible mechanism, but the published evidence is almost entirely vendor marketing. One "
      "case study found during research described a university that does not exist. The one "
      "independent account located &mdash; a student newspaper covering Case Western Reserve's "
      "2017 Luxer One deployment &mdash; reported the room handled a single carrier and "
      "published no security outcome at all.", chip("weak")],
    ],
    title="Popular measures with thin evidence",
    source=cite("immobilise", "piza", "findmy", "pets2006", "cwru", "iu"))

d.box("warn", "A note on source quality encountered during this research",
      "<p>While assembling this report, a smart-locker 'case study' was found attributing "
      "specific figures (a 340% rise in package theft, a fall from 127 incidents per semester "
      "to 3, a 98% reduction) to a named university in San Diego. <b>No such institution "
      "exists.</b> The numbers were excluded.</p>"
      "<p>This is worth stating because the anti-theft technology sector's published evidence "
      "base is heavily contaminated with unverifiable and occasionally fabricated case studies. "
      "Any claim in this space that does not name a real, checkable institution and a real "
      "baseline should be treated as marketing.</p>")

# =========================================================== SECTION 9 ====

d.h2("9. Design implications and candidate solutions", "solutions")
d.p("The evidence converges on a narrow set of principles. What follows ranks candidate "
    "solutions by the strength of the mechanism behind them, not by how impressive they are to "
    "build.")

d.h3("Five principles the data supports")
d.ol([
    "<b>Attack disposability first.</b> The strongest measured intervention in this entire "
    "review is Activation Lock, which changed nothing about theft opportunity and everything "
    "about resale value. The UW-Madison ordinance did the same for textbooks. If a stolen thing "
    "cannot be converted to money, the theft stops being worth committing.",
    "<b>Give every object a cheap identity, and make checking it free.</b> Vehicles recover at "
    "56% and everything else at 8% because vehicles have identifiers that are checked routinely. "
    "Registration alone is not enough &mdash; Indiana proved that &mdash; the check has to be "
    "automatic at the moments an item surfaces.",
    "<b>Design for the honest finder, not the thief.</b> Baseline return rates are 40&ndash;72% "
    "and rise with the apparent cost to the owner. Most items in the loss channel are already in "
    "the hands of someone willing to return them who does not know how. That is a routing "
    "problem, and routing problems are tractable.",
    "<b>Target bounded spaces, not open ones.</b> Every significant effect in the meta-analyses "
    "came from enclosed, bounded settings. Libraries, gyms, bike compounds and residence halls "
    "are the campus equivalents of the car parks where CCTV works.",
    "<b>Reduce the guardianship gap rather than punishing it.</b> The dominant mechanism is a "
    "few minutes of absence. Anything that shortens that gap, or substitutes a guardian during "
    "it, addresses the majority of incidents.",
])

d.h3("Candidate solutions, ranked by evidential support")

d.table(
    ["Candidate", "Mechanism it exploits", "Evidence behind the mechanism", "Main failure mode"],
    [
     ["<b>1. Campus-wide claim identity on portable property</b><br>"
      "<small>A durable tag (QR/NFC) bound to the institutional identity system, so any finder "
      "with a phone can route an item to its owner without learning who they are.</small>",
      "Identifiability drives recovery; finders are honest but unrouted",
      "TfL reclaim spread (48.3% phones vs 2.3% umbrellas); Cohn et al. 40&ndash;72% return "
      "rates; FBI Table 24 vehicle vs non-vehicle recovery",
      "Coverage. A tag on 5% of objects helps 5% of cases. Needs to ride on something students "
      "already do &mdash; enrolment, ID issue, bike registration."],
     ["<b>2. Automatic checking at resale and surfacing points</b><br>"
      "<small>Make the campus second-hand market, the bike impound, the lost-and-found and the "
      "local buy-back shops check the registry as a routine step.</small>",
      "Disposability is the binding constraint on theft value",
      "Activation Lock natural experiment (&minus;38% SF iPhone robberies); UW-Madison "
      "second-hand ordinance (&minus;86% incidents)",
      "Requires institutional and possibly municipal cooperation. This is a policy artefact as "
      "much as a software one &mdash; which is why it works."],
     ["<b>3. Shorten the guardianship gap in bounded spaces</b><br>"
      "<small>Lockers, tethers, and 'watch my stuff' pairing in libraries and gyms, deployed "
      "where the density of unattended property is highest.</small>",
      "Unattended-property theft is the dominant mechanism",
      "69% of UW-Madison thefts from unattended bags; University of Miami Police &gt;50% of all "
      "campus crime; CCTV car-park analogue (&minus;37%)",
      "Behaviour change is hard to sustain past week three. Physical infrastructure outlasts "
      "campaigns."],
     ["<b>4. Front-load intervention on the academic calendar</b><br>"
      "<small>Concentrate lock giveaways, registration drives and messaging on the first six "
      "weeks.</small>",
      "Strong, measured seasonality",
      f"Indiana University: {D.IU_SEASON[0][1]}% of bike incidents in August and "
      f"{D.IU_SEASON[1][1]}% in September",
      "Cheap and evidenced, but it is an amplifier for other measures rather than a solution on "
      "its own."],
     ["<b>5. Reporting that is worth the victim's time</b><br>"
      "<small>One-tap reporting that produces something useful immediately &mdash; a registry "
      "flag, an insurance-ready record, an alert to resale channels.</small>",
      "Non-reporting is the largest single leak in the funnel",
      f"{pct(D.NCVS_TOTAL_REPORTED)} of US property crime reported; "
      f"{D.IU_BIKE['not_reported']}% of IU bike victims reported nothing at all; UW-Madison "
      "found students did not report due to low confidence in recovery",
      "If reporting still produces nothing, the second-order effect is worse than not asking."],
     ["<b>6. Crowdsourced location tracking</b><br>"
      "<small>Piggyback on existing finding networks rather than building one.</small>",
      "Dense device populations can localise offline objects",
      f"Find My measured performance: {D.FINDMY['walk_smoothed_m']:.0f}m smoothed error walking "
      f"in a city from {D.FINDMY['walk_reports']} reports",
      "Location is not custody, coverage collapses outside dense areas, and unwanted-tracking "
      "obligations apply. Useful as a component, dangerous as the core idea."],
    ],
    title="Candidate solutions ranked by mechanism strength",
    sub="Ranked by how well the underlying mechanism is evidenced, not by novelty or "
        "buildability. The top two are the least technically interesting and the most likely to "
        "work.",
    source=cite("tfl", "cohn", "fbi_t24", "sos", "uwpd", "iu", "bjs", "findmy", "umpd"))

d.box("warn", "Constraints any student-built system must respect",
      "<ul>"
      "<li><b>Unwanted tracking.</b> Any Bluetooth-locatable tag falls under the Apple/Google "
      "unwanted-tracker specification, currently an IETF Internet-Draft. It sets obligations "
      "for small trackers &mdash; those under "
      f"{D.IETF_THRESHOLDS['one_dim_cm']}cm in one dimension, "
      f"{D.IETF_THRESHOLDS['two_dim']} in two, or {D.IETF_THRESHOLDS['volume_cm3']}cm&sup3; "
      "&mdash; covering advertising behaviour, MAC rotation, non-owner discovery, and the "
      "ability for a stalking victim to find and disable the tag. Building a tracker without "
      "implementing this is building a stalking device.</li>"
      "<li><b>Broadcast identifiers are abusable.</b> The Send My research demonstrated that "
      "arbitrary data can be piggybacked through Apple's Find My network because the BLE "
      "public-key broadcasts are neither authenticated nor encrypted. Assume any identifier you "
      "broadcast will be logged, replayed and repurposed.</li>"
      "<li><b>Surveillance is not free.</b> Campus CCTV expansion carries data-protection duties "
      "and a real community-trust cost, and the meta-analytic evidence does not support open-"
      "space camera deployment anyway. Prefer measures that do not require watching people.</li>"
      "<li><b>Privacy in the recovery flow itself.</b> A finder must be able to return an item "
      "without learning the owner's name, address or timetable. Route through the institution, "
      "never expose the owner directly.</li>"
      "</ul>"
      + cite("ietf", "sendmy"))

# ========================================================== SECTION 10 ====

d.h2("10. Limitations and evidence gaps", "limits")
d.ul([
    "<b>The best campus larceny data is old or local.</b> The UW-Madison study dates from 2006"
    "&ndash;08. It is used here because it is the most methodologically detailed campus theft "
    "study located, not because it is current.",
    "<b>US larceny composition is from 2019.</b> The FBI's transition from summary UCR to NIBRS "
    "disrupted the comparable national series; 2019 is the last clean year for the full "
    "nine-category percentage distribution.",
    "<b>TfL data is from 2018/19.</b> It is used because it is the only lost-property source "
    "located that publishes found <i>and</i> reclaimed counts by category &mdash; the pairing "
    "that makes the identity finding possible.",
    "<b>Method prevalence is largely unmeasured.</b> No official collection reviewed records "
    "theft tradecraft. The absence of percentages in Section 5 is a real gap in the world's "
    "statistics, and any source offering confident numbers there should be treated with "
    "suspicion.",
    "<b>Offender composition on campus is unknown.</b> No reliable data on the share of campus "
    "theft committed by outsiders versus students, nor on tailgating prevalence, was located in "
    "primary sources.",
    "<b>UK snatch-theft incidence is suppressed.</b> ONS disclosure control blocks the "
    "stealth-versus-snatch incidence split at an unweighted base of 34.",
    "<b>The funnel chart composites different collections.</b> Its stages come from a victim "
    "survey, police clearance records and an agency property return, across different years and "
    "samples. It is a scale diagram, not a cohort study.",
    "<b>The Activation Lock evidence is uncontrolled.</b> Large, consistent and directionally "
    "convincing &mdash; but administrative trend data published by an advocacy initiative, "
    "without controls or confidence intervals.",
    "<b>The CSEW excludes communal establishments</b>, including student halls of residence, so "
    "UK survey figures under-represent exactly the population this report targets.",
])

# ============================================================ APPENDIX ====

d.h2("Appendix: sources", "sources")
d.p("Every source below was opened and read during preparation. A tick (&#10003;) marks sources "
    "the author opened personally to verify a load-bearing figure, rather than accepting a "
    "research assistant's extraction.")

_rows = []
for k, (label, org, url, kind, year) in sorted(D.SOURCES.items(), key=lambda x: x[1][1]):
    tick = ' &#10003;' if k in D.VERIFIED_BY_LEAD else ""
    _rows.append([f"{org}{tick}", f'<a href="{url}">{label}</a>', year, chip(kind)])
d.table(["Organisation", "Publication", "Period", "Type"], _rows,
        title="Primary sources", sub=f"{len(D.SOURCES)} sources.",
        source="<b>Reproducibility:</b> all figures in this report are held in "
               "<code>research/data.py</code> with their source keys; charts are generated by "
               "<code>research/charts.py</code>; the document is assembled by "
               "<code>research/build_report.py</code>. Rebuild with "
               "<code>python3 research/build_report.py</code>.")

d.raw(
    '<div class="footer"><p><b>How this report was built.</b> Six parallel research streams '
    "covering non-theft loss, macro theft statistics, campus theft, theft methods, intervention "
    "effectiveness and emerging solutions. Each was required to open primary sources directly "
    "and label every figure verified or unverified. Contradictions between streams were "
    "resolved by the author against the primary source &mdash; in one case two streams reported "
    "different NCVS reporting rates, and the published table (29.9% for property crime, 24.8% "
    "for other theft) settled it. One fabricated vendor case study was identified and "
    "excluded.</p>"
    "<p><b>Rebuild:</b> <code>python3 research/build_report.py</code>. "
    "<b>Revert:</b> delete <code>research/</code> &mdash; nothing outside that folder was "
    "modified.</p></div>")

# ============================================================== WRITE =====

_mast = (MASTHEAD.replace("__NSRC__", str(len(D.SOURCES)))
         .replace("__NFIG__", str(d.fig_n)).replace("__NTAB__", str(d.tab_n)))
OUT.write_text(d.html("How people lose their things — and why they never get them back",
                      _mast), encoding="utf-8")
print(f"wrote {OUT}  ({OUT.stat().st_size:,} bytes, "
      f"{d.fig_n} figures, {d.tab_n} tables, {len(D.SOURCES)} sources)")
